config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root "dashboard#home", as: "root"

  get "blogs#homeBlogs", to: "blogs#homeBlogs",  as: "public"



  get "/index/usuarios", to: "users#index", as: "indexUsers"

  get "/newUsuario", to: "users#newUser", as: "newUser"

  post "/createUsuario", to: "users#create", as: "createUser"
  
  get "/showUsuario", to: "users#show", as: "showUser"

  get "/Usuario/:id", to: "users#edit", as: "editUser"

  put "/Usuario/update/:id", to: "users#update", as: "updateUser"

  patch "/Usuario/update/:id", to: "users#update"

  delete "/Usuario/delete/:id_user", to: "users#delete", as: "deleteUser"



  get "/blog", to: "blogs#index", as: "indexBlogs"

  get "/showBlog/:id_blog", to: "blogs#showBlog", as: "showBlog"

  get "/showBlogAdmin/:id_blog", to: "blogs#showBlogAdmin", as: "showBlogAdmin"

  get "/newBlog", to: "blogs#newBlog", as: "newBlogs", as: "newBlog"

  post "/createBlog", to: "blogs#createBlog", as: "createBlog"

  get "/Blog/edit/:id", to: "blogs#editBlog", as: "editBlog"

  put "/Blog/updateBlog/:id", to: "blogs#updateBlog", as: "updateBlog"

  patch "/Blog/updateBlog/:id", to: "blogs#updateBlog"

  delete "/Blog/deleteBlog/:id", to: "blogs#deleteBlog", as: "deleteBlog"


  #get "/comentarios", to: "comentarios#index", as: "indexComentarios"

  post "/addComentario", to: "blogs#addComentario", as: "addComentario"

  delete "/Comentario/delete/:id_comentario", to: "blogs#deleteComentario", as: "deleteComentario" 

  #password_digest
  #password_digest
  #<%= image_tag image.portada.thumb.url, :class=>'figure-img img-fluid rounded' %>

  get "/categoria", to: "categoria_blogs#index", as: "indexCategoria"

  get "/newCategoria", to: "categoria_blogs#newCategoria", as: "newCategoria"

  post "/createCategoria", to: "categoria_blogs#createCategoria", as: "createCategoria"

  get "/Categoria/:id_categoria", to: "categoria_blogs#editCategoria", as: "editCategoria"

  put "/Categoria/update/:id_categoria", to: "categoria_blogs#updateCategoria", as: "updateCategoria"

  patch "/Categoria/update/:id_categoria", to: "categoria_blogs#updateCategoria"

  delete "/Categoria/delete/:id_categoria", to: "categoria_blogs#deleteCategoria", as: "deleteCategoria"





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :picture, PictureUploader
	#belongs_to :categoria_blog
	has_many :categoria_blogs
end

app/models/categoria_blog.rb
class CategoriaBlog < ApplicationRecord
	#has_many :blogs
	belongs_to :blogs

end

app/models/comentario.rb
class Comentario < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


	def homeBlogs 
		@blogs = Blog.all
	end 

	def index
		@blogs = Blog.all
	end



	def showBlog
		@blog = Blog.find(params[:id_blog])
		$id_blog = @blog.id
		@comentarios = Comentario.where(id_blog: @blog.id)
		@comentario = Comentario.new
	end


	def showBlogAdmin
		@blog = Blog.find(params[:id_blog])
		$id_blog = @blog.id
		@comentarios = Comentario.where(id_blog: @blog.id)
		@comentario = Comentario.new
	end

	def addComentario
		@comentario = Comentario.new(comentario_params)
		if @comentario.save
			redirect_to showBlog_path($id_blog)
		else 
			render :showBlog
		end 
	end 

	def newBlog
		@blog = Blog.new
		@currentUser = current_user.id_user
	end 

	def createBlog
		@blog = Blog.new(blog_params)
		if @blog.save
			redirect_to indexBlogs_path
		else
			render :newBlog
		end 
 	end

 	def editBlog 
 		@blog = Blog.find(params[:id])
		@currentUser = current_user.id_user

 	end

 	def updateBlog
 		@blog = Blog.find(params[:id]) 		
 		if @blog.update(blog_params)
			redirect_to indexBlogs_path
		else
			render :editBlog
		end 
	end 

	def deleteBlog
		@blog = Blog.find(params[:id])
		@blog.destroy

		redirect_to indexBlogs_path
	end

	def deleteComentario
		@comentario = Comentario.find(params[:id_comentario])
		@comentario.destroy

		redirect_to showBlogAdmin_path($id_blog)
	end


	private 
		def blog_params
			params.require(:blog).permit(:titulo, :picture, :contenido, :user_id, :categoria_id)
		end 

	private 
		def comentario_params
			params.require(:comentario).permit(:id_blog, :nombre, :email, :comentario)
		end 

end

app/controllers/categoria_blogs_controller.rb
class CategoriaBlogsController < ApplicationController
	
	def index
		@categorias = CategoriaBlog.all
	end

	def newCategoria
		@categoria = CategoriaBlog.new
	end 

	def createCategoria
		@categoria = CategoriaBlog.new(categoria_params)
		if @categoria.save
			redirect_to indexCategoria_path
		else
			render :newCategoria
		end 
 	end

 	def editCategoria 
 		@categoria = CategoriaBlog.find(params[:id_categoria])
 	end

 	def updateCategoria
 		@categoria = CategoriaBlog.find(params[:id_categoria]) 		
 		if @categoria.update(categoria_params)
			redirect_to indexCategoria_path
		else
			render :editCategoria
		end 
	end 

	def deleteCategoria
		@categoria = CategoriaBlog.find(params[:id_categoria])
		@categoria.destroy
		redirect_to indexCategoria_path
	end

	private
		def categoria_params
			params.require(:categoria).permit(:nombre_categoria)
	end

 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def home
		@blogs = Blog.all
	end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def index
		@usuarios = User.all
	end


	def newUser
		@minimum_password_length = 6
		@usuario = User.new
	end 

	def create
		@usuario = User.new(user_params)
		if @usuario.save
			redirect_to indexUsers_path
		else
			render :newUser
		end 
	end

	def edit
 		#@blog = Blog.find(params[:id_blog])
 	end

 	def update
 		#@blog = Blog.find(params[:id_blog]) 		
 		#if blog.update(blog_params)
			#redirect_to homeBlogs_path
		#else
		#render :editBlog
		#end 
	end 

	def delete
		@user = User.find(params[:id_user])
		@user.destroy
		redirect_to indexUsers_path
	end

	private 
		def user_params
			#params.require(:usuario)permit()
		end  
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController

	def index
		#@usuarios = Usuario.all
	end


	def new
		#@usuario = Usuario.new
		#password = 'the secret password'
		#new_hashed_password = User.new(:password => password).encrypted_password
	end 

	def create
		#@usuario = Usuario.new(blog_params)
		#if usuario.save
			#redirect_to homeBlogs_path
		#else
		#render :newBlog
		#end 
	end

	def edit
 		#@blog = Blog.find(params[:id_blog])
 	end

 	def update
 		#@blog = Blog.find(params[:id_blog]) 		
 		#if blog.update(blog_params)
			#redirect_to homeBlogs_path
		#else
		#render :editBlog
		#end 
	end 

	def delete
		#@blog = Blog.find(params[:id_blog])
		#@blog.destroy
		#redirect_to homeBlog
	end

	private 
		def usuario_params
			#params.require(:usuario).permit()
	end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
	def categorias_for_select
		CategoriaBlog.pluck(:nombre_categoria, :id_categoria)
	end
end

app/helpers/categoria_blogs_helper.rb
module CategoriaBlogsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/blogs/editBlog.html.erb
<div class="container mt-5">
  <div class="row mt-5">
    <div class="col-md-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <div class="container">
            <h2 align="center">Edit Blog</h2>

            <%= form_for @blog, url: updateBlog_path do |f| %>

            <div class="field">
              <%= f.label :titulo %><br />
              <%= f.text_field :titulo, autofocus: true, autocomplete: "titulo", :class =>"form-control" , :required =>"on"%>
            </div>

            <div class="field">
              <%= f.label :portada %><br />
              <%= f.text_field :portada, autofocus: true, autocomplete: "portada", :class =>"form-control" , :required =>"on"%>
            </div>

            <div class="field">
              <%= f.label :contenido %><br />
              <%= f.text_area :contenido, autofocus: true, autocomplete: "contenido", :class =>"form-control" , :required =>"on"%>
            </div>

            <div class="field">
              <%= f.label :categoria %><br />
              <%= f.select(:categoria_id, categorias_for_select,{include_blank: "Seleccione Categoria"}, :class =>"form-control"  ) %>
              <%= f.hidden_field  :user_id,  value: @currentUser%>

            </div>

            <div class="actions">
              <%= f.submit "Update", :class =>"btn btn-block btn-info mt-4" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/homeBlogs.html.erb
<style type="text/css">
	a{
		color: #ffff;
		text-decoration: none;
	}
	a:hover{
		color: #ffff;
		text-decoration: none;
	}
</style>
<div class="container mt-5">
	<div class="row">
		<div class="col-md-12">
			<div class="card mt-3">
				<div class="card-body">
					<% @blogs.each do |blog| %>
					<div class="card mt-3">
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-md-6">
									<%= image_tag blog.picture.thumb.url, :class=>'figure-img img-fluid rounded' %>
											
									</div>
									<div class="col-md-6">
										Title: <%= blog.titulo %><br>	
										Categoria: <%= blog.categoria_id %><br>	
										Usuario: <%= blog.user_id %><br>	
									</div>
									<div class="col-md-12">
										Contenido: <%= blog.contenido %><br>										
									</div>
									<div class="col-md-4 mx-auto">
										<button class="btn btn-secondary btn-sm mt-3"><%= link_to "Comentarios", showBlog_path(blog.id), :class=>"link" %></button>
									</div>
								</div>
							</div>
						</div>
					</div>
					<%end%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/blogs/index.html.erb
<style type="text/css">
	a{
		color: #ffff;
		text-decoration: none;
	}
	a:hover{
		color: #ffff;
		text-decoration: none;
	}
	
</style>
<div class="container mt-5">
	<a href="<%= newBlog_path %>"><button class="btn btn-info">Add Blog</button></a>
	<table class="table table-hover table-stripped mt-5">
		<thead>
			<tr>
				<td>Titulo</td>
				<td>Portada</td>
				<td>Categoria</td>
				<td>Usuario</td>
				<td>Fecha de Creación</td>
				<td>Show</td>
				<td>Edit</td>
				<td>Destroy</td>
			</tr>
		</thead>
		<tbody>
			<% @blogs.each do |blog|%>
			<tr>
				<td><%=blog.titulo%></td>
				<td><%= image_tag blog.picture.small.url, :class=>'figure-img img-fluid img-sm rounded' %></td>
				<td><%=blog.categoria_id%></td>
				<td><%=blog.user_id%></td>
				<td><%=blog.created_at%></td>
				<td><button class="btn btn-info"><%= link_to "SHOW", showBlogAdmin_path(blog.id), :class=>"link" %></button></td>
				<td><button class="btn btn-secondary"><%= link_to "EDIT", editBlog_path(blog.id), :class=>"link" %></button></td>
				<td><button class="btn btn-danger"><%= link_to "DELETE", deleteBlog_path(blog.id), :class=>"link", method: :delete, data: { confirm: "¿Estás seguro de eliminar este Blog?" } %></button></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/blogs/newBlog.html.erb
<div class="container mt-5">
  <div class="row mt-5">
    <div class="col-md-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <div class="container">
            <h2 align="center">New Blog</h2>

            <%= form_for(@blog, html:{multipart: true}, url: createBlog_path) do |f| %>

            <div class="field">
              <%= f.label :titulo %><br />
              <%= f.text_field :titulo, autofocus: true, autocomplete: "titulo", :class =>"form-control" , :required =>"on"%>
            </div>

            <div class="field">
              <%= f.label :picture %><br />
              <%= f.text_field :picture %>
            </div>

            <div class="field">
              <%= f.label :contenido %><br />
              <%= f.text_area :contenido, autofocus: true, autocomplete: "contenido", :class =>"form-control" , :required =>"on"%>
            </div>

            <div class="field">
              <%= f.label :categoria %><br />
              <%= f.select(:categoria_id, categorias_for_select,{include_blank: "Seleccione Categoria"}, :class =>"form-control"  ) %>
              <%= f.hidden_field  :user_id,  value: @currentUser%>

            </div>

            <div class="actions">
              <%= f.submit "Add", :class =>"btn btn-block btn-info mt-4" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/showBlog.html.erb
<style type="text/css">
	a{
		color: #ffff;
		text-decoration: none;
	}
	a:hover{
		color: #ffff;
		text-decoration: none;
	}
</style>
<div class="container mt-5">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div class="card">
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-md-6">
									<%= image_tag @blog.picture.thumb.url, :class=>'figure-img img-fluid rounded' %></div>
									<div class="col-md-6">
										Titulo: <%= @blog.titulo %><br>	
										Categoria: <%= @blog.categoria_id %><br>	
										Usuario: <%= @blog.user_id %><br>	
									</div>
									<div class="col-md-12">
										Contenido: <%= @blog.contenido %><br>										
									</div>
									<div class="col-md-12 text-right">
										<button class="btn btn-secondary btn-sm"><%= link_to "Back", public_path %></button>
									</div>
								</div>
							</div>
						</div>
					</div>

					<% @comentarios.each do |coment| %>
					<div class="card mt-2">
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-md-6">
										<span class="badge badge-success"><%= coment.nombre%></span>
									</div>
									<div class="col-md-6">
										<span class="badge badge-info"><%= coment.email%></span>
									</div>
									<div class="col-md-12">
										<%= coment.comentario%>
									</div>
								</div>
							</div>
						</div>
					</div>
					<%end%>

					<div class="card mt-5">
						<div class="card-body">
							<div class="container">
								<%= form_for @comentario, url: addComentario_path do |f| %>
								<div class="row">
									<div class="col-md-6">
										<%= f.label :nombre %><br/>
										<%= f.text_field :nombre, autofocus: true, autocomplete: "Nombre", :class =>"form-control input-sm" %>
									</div>
									<div class="col-md-6">
										<%= f.label :email %><br/>
										<%= f.text_field :email, autofocus: true, autocomplete: "Email", :class =>"form-control input-sm" %>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<%= f.label :comentario %><br/>
										<%= f.text_area :comentario, autofocus: true, autocomplete: "Comentario", :class =>"form-control input-sm" %>
										<%= f.hidden_field :id_blog, value: @blog.id_blog, :class =>"form-control input-sm" %>
									</div>
									<div class="col-md-6">
										<%= f.submit "Comentar", :class =>"btn btn-block btn-info mt-5 btn-sm" %>
									</div>
								</div>
								<% end %>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>

</div>

app/views/blogs/showBlogAdmin.html.erb
<style type="text/css">
	a{
		color: #ffff;
		text-decoration: none;
	}
	a:hover{
		color: #ffff;
		text-decoration: none;
	}
	
</style>
<div class="container mt-5">
	<div class="row">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">
					<div class="card">
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-md-6">
									<%= image_tag @blog.picture.thumb.url, :class=>'figure-img img-fluid rounded' %>
										
									</div>
									<div class="col-md-6">
										Titulo: <%= @blog.titulo %><br>	
										Categoria: <%= @blog.categoria_id %><br>	
										Usuario: <%= @blog.user_id %><br>	
									</div>
									<div class="col-md-12">
										Contenido: <%= @blog.contenido %><br>										
									</div>
									<div class="col-md-12 text-right">
										<button class="btn btn-secondary btn-sm"><%= link_to "Back", indexBlogs_path %></button>
									</div>
								</div>
							</div>
						</div>
					</div>

					<% @comentarios.each do |coment| %>
					<div class="card mt-2">
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-md-4">
										<span class="badge badge-success"><%= coment.nombre%></span>
									</div>
									<div class="col-md-4">
										<span class="badge badge-info"><%= coment.email%></span>
									</div>
									<div class="col-md-4">
										<span class="badge badge-danger"><%= link_to "Eliminar Comentario", deleteComentario_path(coment.id_comentario), :class=>"link", method: :delete, data: { confirm: "¿Estás seguro de eliminar este Comentario?" } %></span>
									</div>
									</div>
									<div class="row">
									<div class="col-md-12">
										<%= coment.comentario%>
									</div>
								</div>
							</div>
						</div>
					</div>
					<%end%>


				</div>
			</div>
		</div>
	</div>

</div>

app/views/categoria_blogs/editCategoria.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card">
        <div class="container">
          <%= form_for @categoria, url: updateCategoria_path do |f| %>
          <div class="row">
            <div class="col-md-12">
              <%= f.label :nombre_categoria %>
              <%= f.text_field :nombre_categoria, :class =>"form-control" %>
            </div>

            <div class="col-md-12">
              <%= f.submit :class => "btn btn-block btn-info mt-4" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categoria_blogs/index.html.erb
<style type="text/css">
	a{
		color: #ffff;
		text-decoration: none;
	}
	a:hover{
		color: #ffff;
		text-decoration: none;
	}
	
</style>
<div class="container mt-5">
	<a href="<%= newCategoria_path %>"><button class="btn btn-info">New Category</button></a>
	<table class="table table-hover table-stripped mt-5">
		<thead>
			<tr>
				<td>Categoria</td>
				<td>Fecha de Creación</td>
				<td>Edit</td>
				<td>Destroy</td>
			</tr>
		</thead>
		<tbody>
			<% @categorias.each do |categoria|%>
			<tr>
				<td><%=categoria.nombre_categoria%></td>
				<td><%=categoria.created_at%></td>
				<td><button class="btn btn-secondary"><%= link_to "EDIT", editCategoria_path(categoria.id_categoria), :class=>"link" %></button></td>
				<td><button class="btn btn-danger"><%= link_to "DELETE", deleteCategoria_path(categoria.id_categoria), :class=>"link", method: :delete, data: { confirm: "¿Estás seguro de eliminar esta Categoria?" } %></button></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/categoria_blogs/newCategoria.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card">
        <div class="card-body">
          <div class="container">
            <h2 align="center">New Category</h2>
            <%= form_for @categoria, url: createCategoria_path do |f| %>
            <div class="row">
              <div class="col-md-12">
                <%= f.label :nombre_categoria %>
                <%= f.text_field :nombre_categoria, :class =>"form-control", :required =>"on" %>
              </div>
              <div class="col-md-12">
                <%= f.submit "Add Category", :class => "btn btn-block btn-info mt-4" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/home.html.erb
	<%= render :partial => 'layouts/components' %>
	<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
	<% end %>
	
	<div class="container mt-5">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-body">
						<div class="container">
							<div class="row">
								<div class="col-md-6 mx-auto">
									<h1>Blog Ruby On Rails</h1>
								</div>
								<div class="col-md-12">
									<p class="text-justify">
										Ruby On Rails es un framework de programación creado por David Heinemeier Hansson, quien le dio el nombre de Ruby on Rails, que usualmente es llamando simplemente Rails.

										Rails está enfocado en crear sitios web y combina Ruby con HTML, CSS y JavaScript para crear aplicaciones web que corren en un servidor web. Dado lo anterior, es considerado server-side o Back-end.

										Ruby on Rails más que un framework es el proyecto central de una comunidad gigante que produce de manera constante librerías para simplificar las tareas de crear complejas aplicaciones web.
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/layouts/_components.html.erb
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

app/views/layouts/_navbar.html.erb
 <!-- Load an icon library to show a hamburger menu (bars) on small screens -->

 <style type="text/css">
   /* Style the navigation menu */
   .topnav {
    overflow: hidden;
    background-color: #333;
    position: relative;
  }

  .topnav #myLinks {
    display: none;
  }

  .topnav a {
    color: white;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 15px;
    display: block;
  }

  .topnav a.icon {
    background: black;
    position: absolute;
    left: 1300px;
    right: 0;
    top: 0;
    bottom: 0;
  }

  .topnav a:hover {
    background-color: #333;
    color: black;
  }

  .active {
    background-color: #4CAF50;
    color: white;
  } 
</style>
<div class="topnav">
  <div id="myLinks">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Registrar Usuario", newUser_path, :class => 'navbar-link'  %> |
    <%= link_to "Usuarios", indexUsers_path, :class => 'navbar-link'  %> |
    <%= link_to "Admin Blogs", indexBlogs_path, :class => 'navbar-link'  %> |
    <%= link_to "Categorias", indexCategoria_path, :class => 'navbar-link'  %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> 
    <% else %>
    <%= link_to "Ver Blogs", public_path, :class => 'navbar-link'  %> |
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>

    <% end %>
  </div>
  <div align="right">
    <a href="javascript:void(0);" onclick="myFunction()"><button class="btn btn-outline-light btn-sm">ClickMe</button></a>
  </div>
</div>

<script type="text/javascript">
  function myFunction() {
    var x = document.getElementById("myLinks");
    if (x.style.display === "block") {
      x.style.display = "none";
    } else {
      x.style.display = "block";
    }
  } 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Blog</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= render :partial => 'layouts/components' %>

</head>
<body>
	<%= render :partial => 'layouts/navbar' %>

	<% if notice %>
	<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	<p class="alert alert-danger"><%= alert %></p>
	<% end %>

	<%= yield %>
	</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Dashboard</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= render :partial => 'layouts/navbar' %>
	
</head>
<body>
	<%= yield %>
</body>
</html>